# coding: utf-8

"""
    Layar API Documentation

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: VERSION_PLACEHOLDER
    Contact: support@vyasa.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import layar_api
from layar_api.models.body7 import Body7  # noqa: E501
from layar_api.rest import ApiException


class TestBody7(unittest.TestCase):
    """Body7 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBody7(self):
        """Test Body7"""
        # FIXME: construct object with mandatory attributes with example values
        # model = layar_api.models.body7.Body7()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
