# coding: utf-8

"""
    Layar API Documentation

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import layar_api
from layar_api.api.clustered_statements_api import ClusteredStatementsApi  # noqa: E501
from layar_api.rest import ApiException


class TestClusteredStatementsApi(unittest.TestCase):
    """ClusteredStatementsApi unit test stubs"""

    def setUp(self):
        self.api = ClusteredStatementsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create(self):
        """Test case for create

        create a new clustered statement request  # noqa: E501
        """
        pass

    def test_get(self):
        """Test case for get

        clustered statements details  # noqa: E501
        """
        pass

    def test_get_statements(self):
        """Test case for get_statements

        statements  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
