# coding: utf-8

"""
    Layar API Documentation

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import layar_api
from layar_api.models.bulk_question import BulkQuestion  # noqa: E501
from layar_api.rest import ApiException


class TestBulkQuestion(unittest.TestCase):
    """BulkQuestion unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBulkQuestion(self):
        """Test BulkQuestion"""
        # FIXME: construct object with mandatory attributes with example values
        # model = layar_api.models.bulk_question.BulkQuestion()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
