# coding: utf-8

"""
    Layar API Documentation

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: VERSION_PLACEHOLDER
    Contact: AI-Support@Certara.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import layar_api
from layar_api.models.inline_response2001_documents_used import InlineResponse2001DocumentsUsed  # noqa: E501
from layar_api.rest import ApiException


class TestInlineResponse2001DocumentsUsed(unittest.TestCase):
    """InlineResponse2001DocumentsUsed unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2001DocumentsUsed(self):
        """Test InlineResponse2001DocumentsUsed"""
        # FIXME: construct object with mandatory attributes with example values
        # model = layar_api.models.inline_response2001_documents_used.InlineResponse2001DocumentsUsed()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
