# coding: utf-8

"""
    Layar API Documentation

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import layar_api
from layar_api.api.statement_api import StatementApi  # noqa: E501
from layar_api.rest import ApiException


class TestStatementApi(unittest.TestCase):
    """StatementApi unit test stubs"""

    def setUp(self):
        self.api = StatementApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create(self):
        """Test case for create

        save  # noqa: E501
        """
        pass

    def test_delete(self):
        """Test case for delete

        delete  # noqa: E501
        """
        pass

    def test_delete_many(self):
        """Test case for delete_many

        deleteMany  # noqa: E501
        """
        pass

    def test_get(self):
        """Test case for get

        statement details  # noqa: E501
        """
        pass

    def test_get_field_counts(self):
        """Test case for get_field_counts

        """
        pass

    def test_get_relationship_evidence(self):
        """Test case for get_relationship_evidence

        relationshipEvidence  # noqa: E501
        """
        pass

    def test_search(self):
        """Test case for search

        search for statements  # noqa: E501
        """
        pass

    def test_update(self):
        """Test case for update

        update  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
