# coding: utf-8

"""
    Layar API Documentation

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import layar_api
from layar_api.models.paragraph_search_command import ParagraphSearchCommand  # noqa: E501
from layar_api.rest import ApiException


class TestParagraphSearchCommand(unittest.TestCase):
    """ParagraphSearchCommand unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testParagraphSearchCommand(self):
        """Test ParagraphSearchCommand"""
        # FIXME: construct object with mandatory attributes with example values
        # model = layar_api.models.paragraph_search_command.ParagraphSearchCommand()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
