# coding: utf-8

"""
    Layar API Documentation

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ConceptTermAssignment(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'concept_type_id': 'str',
        'id': 'str',
        'term': 'str',
        'user_id': 'int'
    }

    attribute_map = {
        'concept_type_id': 'conceptTypeId',
        'id': 'id',
        'term': 'term',
        'user_id': 'userId'
    }

    def __init__(self, concept_type_id=None, id=None, term=None, user_id=None):  # noqa: E501
        """ConceptTermAssignment - a model defined in Swagger"""  # noqa: E501
        self._concept_type_id = None
        self._id = None
        self._term = None
        self._user_id = None
        self.discriminator = None
        if concept_type_id is not None:
            self.concept_type_id = concept_type_id
        if id is not None:
            self.id = id
        if term is not None:
            self.term = term
        if user_id is not None:
            self.user_id = user_id

    @property
    def concept_type_id(self):
        """Gets the concept_type_id of this ConceptTermAssignment.  # noqa: E501


        :return: The concept_type_id of this ConceptTermAssignment.  # noqa: E501
        :rtype: str
        """
        return self._concept_type_id

    @concept_type_id.setter
    def concept_type_id(self, concept_type_id):
        """Sets the concept_type_id of this ConceptTermAssignment.


        :param concept_type_id: The concept_type_id of this ConceptTermAssignment.  # noqa: E501
        :type: str
        """

        self._concept_type_id = concept_type_id

    @property
    def id(self):
        """Gets the id of this ConceptTermAssignment.  # noqa: E501


        :return: The id of this ConceptTermAssignment.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ConceptTermAssignment.


        :param id: The id of this ConceptTermAssignment.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def term(self):
        """Gets the term of this ConceptTermAssignment.  # noqa: E501


        :return: The term of this ConceptTermAssignment.  # noqa: E501
        :rtype: str
        """
        return self._term

    @term.setter
    def term(self, term):
        """Sets the term of this ConceptTermAssignment.


        :param term: The term of this ConceptTermAssignment.  # noqa: E501
        :type: str
        """

        self._term = term

    @property
    def user_id(self):
        """Gets the user_id of this ConceptTermAssignment.  # noqa: E501


        :return: The user_id of this ConceptTermAssignment.  # noqa: E501
        :rtype: int
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this ConceptTermAssignment.


        :param user_id: The user_id of this ConceptTermAssignment.  # noqa: E501
        :type: int
        """

        self._user_id = user_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ConceptTermAssignment, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ConceptTermAssignment):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
