# coding: utf-8

"""
    Layar API Documentation

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: VERSION_PLACEHOLDER
    Contact: AI-Support@Certara.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class FieldFilterConditions(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'field': 'str',
        'exists': 'bool',
        'min_value': 'float',
        'max_value': 'float',
        'min_date': 'datetime',
        'max_date': 'datetime',
        'values': 'list[str]'
    }

    attribute_map = {
        'field': 'field',
        'exists': 'exists',
        'min_value': 'minValue',
        'max_value': 'maxValue',
        'min_date': 'minDate',
        'max_date': 'maxDate',
        'values': 'values'
    }

    def __init__(self, field=None, exists=None, min_value=None, max_value=None, min_date=None, max_date=None, values=None):  # noqa: E501
        """FieldFilterConditions - a model defined in Swagger"""  # noqa: E501
        self._field = None
        self._exists = None
        self._min_value = None
        self._max_value = None
        self._min_date = None
        self._max_date = None
        self._values = None
        self.discriminator = None
        if field is not None:
            self.field = field
        if exists is not None:
            self.exists = exists
        if min_value is not None:
            self.min_value = min_value
        if max_value is not None:
            self.max_value = max_value
        if min_date is not None:
            self.min_date = min_date
        if max_date is not None:
            self.max_date = max_date
        if values is not None:
            self.values = values

    @property
    def field(self):
        """Gets the field of this FieldFilterConditions.  # noqa: E501


        :return: The field of this FieldFilterConditions.  # noqa: E501
        :rtype: str
        """
        return self._field

    @field.setter
    def field(self, field):
        """Sets the field of this FieldFilterConditions.


        :param field: The field of this FieldFilterConditions.  # noqa: E501
        :type: str
        """

        self._field = field

    @property
    def exists(self):
        """Gets the exists of this FieldFilterConditions.  # noqa: E501


        :return: The exists of this FieldFilterConditions.  # noqa: E501
        :rtype: bool
        """
        return self._exists

    @exists.setter
    def exists(self, exists):
        """Sets the exists of this FieldFilterConditions.


        :param exists: The exists of this FieldFilterConditions.  # noqa: E501
        :type: bool
        """

        self._exists = exists

    @property
    def min_value(self):
        """Gets the min_value of this FieldFilterConditions.  # noqa: E501


        :return: The min_value of this FieldFilterConditions.  # noqa: E501
        :rtype: float
        """
        return self._min_value

    @min_value.setter
    def min_value(self, min_value):
        """Sets the min_value of this FieldFilterConditions.


        :param min_value: The min_value of this FieldFilterConditions.  # noqa: E501
        :type: float
        """

        self._min_value = min_value

    @property
    def max_value(self):
        """Gets the max_value of this FieldFilterConditions.  # noqa: E501


        :return: The max_value of this FieldFilterConditions.  # noqa: E501
        :rtype: float
        """
        return self._max_value

    @max_value.setter
    def max_value(self, max_value):
        """Sets the max_value of this FieldFilterConditions.


        :param max_value: The max_value of this FieldFilterConditions.  # noqa: E501
        :type: float
        """

        self._max_value = max_value

    @property
    def min_date(self):
        """Gets the min_date of this FieldFilterConditions.  # noqa: E501


        :return: The min_date of this FieldFilterConditions.  # noqa: E501
        :rtype: datetime
        """
        return self._min_date

    @min_date.setter
    def min_date(self, min_date):
        """Sets the min_date of this FieldFilterConditions.


        :param min_date: The min_date of this FieldFilterConditions.  # noqa: E501
        :type: datetime
        """

        self._min_date = min_date

    @property
    def max_date(self):
        """Gets the max_date of this FieldFilterConditions.  # noqa: E501


        :return: The max_date of this FieldFilterConditions.  # noqa: E501
        :rtype: datetime
        """
        return self._max_date

    @max_date.setter
    def max_date(self, max_date):
        """Sets the max_date of this FieldFilterConditions.


        :param max_date: The max_date of this FieldFilterConditions.  # noqa: E501
        :type: datetime
        """

        self._max_date = max_date

    @property
    def values(self):
        """Gets the values of this FieldFilterConditions.  # noqa: E501


        :return: The values of this FieldFilterConditions.  # noqa: E501
        :rtype: list[str]
        """
        return self._values

    @values.setter
    def values(self, values):
        """Sets the values of this FieldFilterConditions.


        :param values: The values of this FieldFilterConditions.  # noqa: E501
        :type: list[str]
        """

        self._values = values

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(FieldFilterConditions, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FieldFilterConditions):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
