# coding: utf-8

"""
    Layar API Documentation

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: VERSION_PLACEHOLDER
    Contact: AI-Support@Certara.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse2001(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'type': 'str',
        'content': 'str',
        'sources_used': 'list[str]',
        'documents_used': 'list[InlineResponse2001DocumentsUsed]',
        'chunks_used': 'list[InlineResponse2001ChunksUsed]'
    }

    attribute_map = {
        'type': 'type',
        'content': 'content',
        'sources_used': 'sourcesUsed',
        'documents_used': 'documentsUsed',
        'chunks_used': 'chunksUsed'
    }

    def __init__(self, type=None, content=None, sources_used=None, documents_used=None, chunks_used=None):  # noqa: E501
        """InlineResponse2001 - a model defined in Swagger"""  # noqa: E501
        self._type = None
        self._content = None
        self._sources_used = None
        self._documents_used = None
        self._chunks_used = None
        self.discriminator = None
        if type is not None:
            self.type = type
        if content is not None:
            self.content = content
        if sources_used is not None:
            self.sources_used = sources_used
        if documents_used is not None:
            self.documents_used = documents_used
        if chunks_used is not None:
            self.chunks_used = chunks_used

    @property
    def type(self):
        """Gets the type of this InlineResponse2001.  # noqa: E501


        :return: The type of this InlineResponse2001.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this InlineResponse2001.


        :param type: The type of this InlineResponse2001.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def content(self):
        """Gets the content of this InlineResponse2001.  # noqa: E501


        :return: The content of this InlineResponse2001.  # noqa: E501
        :rtype: str
        """
        return self._content

    @content.setter
    def content(self, content):
        """Sets the content of this InlineResponse2001.


        :param content: The content of this InlineResponse2001.  # noqa: E501
        :type: str
        """

        self._content = content

    @property
    def sources_used(self):
        """Gets the sources_used of this InlineResponse2001.  # noqa: E501


        :return: The sources_used of this InlineResponse2001.  # noqa: E501
        :rtype: list[str]
        """
        return self._sources_used

    @sources_used.setter
    def sources_used(self, sources_used):
        """Sets the sources_used of this InlineResponse2001.


        :param sources_used: The sources_used of this InlineResponse2001.  # noqa: E501
        :type: list[str]
        """

        self._sources_used = sources_used

    @property
    def documents_used(self):
        """Gets the documents_used of this InlineResponse2001.  # noqa: E501


        :return: The documents_used of this InlineResponse2001.  # noqa: E501
        :rtype: list[InlineResponse2001DocumentsUsed]
        """
        return self._documents_used

    @documents_used.setter
    def documents_used(self, documents_used):
        """Sets the documents_used of this InlineResponse2001.


        :param documents_used: The documents_used of this InlineResponse2001.  # noqa: E501
        :type: list[InlineResponse2001DocumentsUsed]
        """

        self._documents_used = documents_used

    @property
    def chunks_used(self):
        """Gets the chunks_used of this InlineResponse2001.  # noqa: E501


        :return: The chunks_used of this InlineResponse2001.  # noqa: E501
        :rtype: list[InlineResponse2001ChunksUsed]
        """
        return self._chunks_used

    @chunks_used.setter
    def chunks_used(self, chunks_used):
        """Sets the chunks_used of this InlineResponse2001.


        :param chunks_used: The chunks_used of this InlineResponse2001.  # noqa: E501
        :type: list[InlineResponse2001ChunksUsed]
        """

        self._chunks_used = chunks_used

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse2001, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse2001):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
