# coding: utf-8

"""
    Layar API Documentation

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: VERSION_PLACEHOLDER
    Contact: support@vyasa.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SourceDocumentImportStatus(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'percent': 'int',
        'message': 'str',
        'error': 'bool'
    }

    attribute_map = {
        'percent': 'percent',
        'message': 'message',
        'error': 'error'
    }

    def __init__(self, percent=None, message=None, error=None):  # noqa: E501
        """SourceDocumentImportStatus - a model defined in Swagger"""  # noqa: E501
        self._percent = None
        self._message = None
        self._error = None
        self.discriminator = None
        if percent is not None:
            self.percent = percent
        if message is not None:
            self.message = message
        if error is not None:
            self.error = error

    @property
    def percent(self):
        """Gets the percent of this SourceDocumentImportStatus.  # noqa: E501


        :return: The percent of this SourceDocumentImportStatus.  # noqa: E501
        :rtype: int
        """
        return self._percent

    @percent.setter
    def percent(self, percent):
        """Sets the percent of this SourceDocumentImportStatus.


        :param percent: The percent of this SourceDocumentImportStatus.  # noqa: E501
        :type: int
        """

        self._percent = percent

    @property
    def message(self):
        """Gets the message of this SourceDocumentImportStatus.  # noqa: E501


        :return: The message of this SourceDocumentImportStatus.  # noqa: E501
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this SourceDocumentImportStatus.


        :param message: The message of this SourceDocumentImportStatus.  # noqa: E501
        :type: str
        """

        self._message = message

    @property
    def error(self):
        """Gets the error of this SourceDocumentImportStatus.  # noqa: E501


        :return: The error of this SourceDocumentImportStatus.  # noqa: E501
        :rtype: bool
        """
        return self._error

    @error.setter
    def error(self, error):
        """Sets the error of this SourceDocumentImportStatus.


        :param error: The error of this SourceDocumentImportStatus.  # noqa: E501
        :type: bool
        """

        self._error = error

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SourceDocumentImportStatus, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SourceDocumentImportStatus):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
