# coding: utf-8

"""
    Layar API Documentation

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: VERSION_PLACEHOLDER
    Contact: support@vyasa.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class StatementNamedEntityCommand(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'column_keys': 'list[str]'
    }

    attribute_map = {
        'column_keys': 'columnKeys'
    }

    def __init__(self, column_keys=None):  # noqa: E501
        """StatementNamedEntityCommand - a model defined in Swagger"""  # noqa: E501
        self._column_keys = None
        self.discriminator = None
        if column_keys is not None:
            self.column_keys = column_keys

    @property
    def column_keys(self):
        """Gets the column_keys of this StatementNamedEntityCommand.  # noqa: E501


        :return: The column_keys of this StatementNamedEntityCommand.  # noqa: E501
        :rtype: list[str]
        """
        return self._column_keys

    @column_keys.setter
    def column_keys(self, column_keys):
        """Sets the column_keys of this StatementNamedEntityCommand.


        :param column_keys: The column_keys of this StatementNamedEntityCommand.  # noqa: E501
        :type: list[str]
        """

        self._column_keys = column_keys

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(StatementNamedEntityCommand, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, StatementNamedEntityCommand):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
